// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://votwokvmqroxidvokexh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvdHdva3ZtcXJveGlkdm9rZXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3Mzg5NTYsImV4cCI6MjA3MDMxNDk1Nn0.QaL3H6AeY40vRUjAIDTzCIcYuKqqZbtXwIp9G5_-bdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});